server {
    listen 8093;

    root /usr/share/nginx/html;
    error_page 404 /404.html;
    rewrite ^([^.]*[^/])$ $1/ permanent;
    absolute_redirect off;

    add_header Content-Security-Policy "frame-ancestors 'self';";

    location / {
        try_files $uri $uri/index.html =404;
    }

    location ~ ^/documentation/documentation/ {
        return 404;
    }

    location /documentation {
        try_files $uri/index.html $uri/ =404;
    }

    location /documentation/sitemap.xml {
        try_files $uri =404;
    }

    location /documentation/getting-form-data/ {
        return 301 https://formengine.io/documentation/form-data/;
    }

    location /pricing {
        return 301 https://formengine.io/react-form-builder-library/pricing;
    }

    location ~ \.(jpg|jpeg|gif|png|ico|bmp|cur|svg|zip|tgz|gz|rar|bz2|doc|xls|pdf|ppt|txt|rtf|tar|wav|mp3|ogg|avi|mov|mp4|ogv|webm|htc|flv|swf|js|css) {
        access_log off;
        expires modified +1y;
        add_header Cache-Control public;
        etag on;
        try_files $uri =404;
    }

    location /backend/ {
        include fastcgi_params;
        fastcgi_pass formengine-fpm:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
