'use client'

import { PricingCard } from './PricingCard'

const subscriptionPlans = [
  {
    name: 'Core',
    price: 'Free',
    description: 'MIT License, Any Commercial Use',
    cta: 'Start for free',
    features: [
      { label: 'Drag & Drop Form Designer', value: false },
      { label: 'UI customization', value: false },
      { label: 'Localization (Unlimited)', value: true },
      { label: 'Domains (Unlimited)', value: true },
      { label: 'Wildcard (subdomain)', value: true },
      { label: 'JSON Renderer', value: true },
      { label: 'Code Renderer', value: true },
      { label: 'Custom components', value: true },
      { label: 'React Suite library', value: true },
      { label: 'E-sign component', value: false },
      { label: 'QR Code component', value: false },
      { label: 'Grid component', value: false },
      { label: 'Repeater component', value: true },
      { label: 'SaaS use allowed', value: true },
      { label: 'OEM allowed', value: true },
      { label: 'Free updates', value: true },
      { label: 'Source code included', value: true },
    ],
  },
  {
    name: 'StartUp',
    price: '$899 /year',
    description: '1 domain, internal commercial use',
    cta: 'Buy now',
    features: [
      { label: 'Drag & Drop Form Designer', value: true },
      { label: 'UI customization', value: false },
      { label: 'Localization (1 language)', value: true },
      { label: 'Domains (1)', value: true },
      { label: 'Wildcard (subdomain)', value: false },
      { label: 'JSON Renderer', value: true },
      { label: 'Code Renderer', value: true },
      { label: 'Custom components', value: true },
      { label: 'React Suite library', value: true },
      { label: 'E-sign component', value: false },
      { label: 'QR Code component', value: false },
      { label: 'Grid component', value: false },
      { label: 'Repeater component', value: false },
      { label: 'SaaS use allowed', value: false },
      { label: 'OEM allowed', value: false },
      { label: 'Free updates (1 year)', value: true },
      { label: 'Source code included', value: false },
    ],
  },
  {
    name: 'Business',
    price: '$1,499 /year',
    description: '3 domains, internal commercial use',
    cta: 'Buy now',
    features: [
      { label: 'Drag & Drop Form Designer', value: true },
      { label: 'UI customization', value: true },
      { label: 'Localization (3 languages)', value: true },
      { label: 'Domains (3)', value: true },
      { label: 'Wildcard (subdomain)', value: true },
      { label: 'JSON Renderer', value: true },
      { label: 'Code Renderer', value: true },
      { label: 'Custom components', value: true },
      { label: 'React Suite library', value: true },
      { label: 'E-sign component', value: true },
      { label: 'QR Code component', value: true },
      { label: 'Grid component', value: false },
      { label: 'Repeater component', value: false },
      { label: 'SaaS use allowed', value: false },
      { label: 'OEM allowed', value: false },
      { label: 'Free updates (1 year)', value: true },
      { label: 'Source code included', value: false },
    ],
  },
  {
    name: 'Enterprise',
    price: '$3,499 /year',
    description: '5 domains, SaaS use allowed',
    cta: 'Buy now',
    features: [
      { label: 'Drag & Drop Form Designer', value: true },
      { label: 'UI customization', value: true },
      { label: 'Localization (5 languages)', value: true },
      { label: 'Domains (5)', value: true },
      { label: 'Wildcard (subdomain)', value: true },
      { label: 'JSON Renderer', value: true },
      { label: 'Code Renderer', value: true },
      { label: 'Custom components', value: true },
      { label: 'React Suite library', value: true },
      { label: 'E-sign component', value: true },
      { label: 'QR Code component', value: true },
      { label: 'Grid component', value: true },
      { label: 'Repeater component', value: true },
      { label: 'SaaS use allowed', value: true },
      { label: 'OEM allowed', value: false },
      { label: 'Free updates (1 year)', value: true },
      { label: 'Source code included', value: false },
    ],
  },
]

const perpetualPlans = [
  {
    name: 'Core',
    price: 'Free',
    description: 'MIT License, Any Commercial Use',
    cta: 'Start for free',
    features: [
      { label: 'Drag & Drop Form Designer', value: false },
      { label: 'UI customization', value: false },
      { label: 'Localization (Unlimited)', value: true },
      { label: 'Domains (Unlimited)', value: true },
      { label: 'Wildcard (subdomain)', value: true },
      { label: 'JSON Renderer', value: true },
      { label: 'Code Renderer', value: true },
      { label: 'Custom components', value: true },
      { label: 'React Suite library', value: true },
      { label: 'E-sign component', value: false },
      { label: 'QR Code component', value: false },
      { label: 'Grid component', value: false },
      { label: 'Repeater component', value: true },
      { label: 'SaaS use allowed', value: true },
      { label: 'OEM allowed', value: true },
      { label: 'Free updates', value: true },
      { label: 'Source code included', value: true },
    ],
  },
  {
    name: 'StartUp',
    price: '$1,299 /one-time',
    description: '1 domain, 6 months updates, internal commercial use',
    cta: 'Buy now',
    features: [
      { label: 'Drag & Drop Form Designer', value: true },
      { label: 'UI customization', value: false },
      { label: 'Localization (1 language)', value: true },
      { label: 'Domains (1)', value: true },
      { label: 'Wildcard (subdomain)', value: false },
      { label: 'JSON Renderer', value: true },
      { label: 'Code Renderer', value: true },
      { label: 'Custom components', value: true },
      { label: 'React Suite library', value: true },
      { label: 'E-sign component', value: false },
      { label: 'QR Code component', value: false },
      { label: 'Grid component', value: false },
      { label: 'Repeater component', value: false },
      { label: 'SaaS use allowed', value: false },
      { label: 'OEM allowed', value: false },
      { label: 'Free updates (6 months)', value: true },
      { label: 'Source code included', value: false },
    ],
  },
  {
    name: 'Business',
    price: '$2,999 /one-time',
    description: '3 domains, 1 year updates, internal commercial use',
    cta: 'Buy now',
    features: [
      { label: 'Drag & Drop Form Designer', value: true },
      { label: 'UI customization', value: true },
      { label: 'Localization (3 languages)', value: true },
      { label: 'Domains (3)', value: true },
      { label: 'Wildcard (subdomain)', value: true },
      { label: 'JSON Renderer', value: true },
      { label: 'Code Renderer', value: true },
      { label: 'Custom components', value: true },
      { label: 'React Suite library', value: true },
      { label: 'E-sign component', value: true },
      { label: 'QR Code component', value: true },
      { label: 'Grid component', value: false },
      { label: 'Repeater component', value: false },
      { label: 'SaaS use allowed', value: false },
      { label: 'OEM allowed', value: false },
      { label: 'Free updates (1 year)', value: true },
      { label: 'Source code included', value: false },
    ],
  },
  {
    name: 'Enterprise',
    price: '$5,999 /one-time',
    description: 'Unlimited domains, SaaS use allowed, 1 year updates',
    cta: 'Buy now',
    features: [
      { label: 'Drag & Drop Form Designer', value: true },
      { label: 'UI customization', value: true },
      { label: 'Localization (Unlimited)', value: true },
      { label: 'Domains (Unlimited)', value: true },
      { label: 'Wildcard (subdomain)', value: true },
      { label: 'JSON Renderer', value: true },
      { label: 'Code Renderer', value: true },
      { label: 'Custom components', value: true },
      { label: 'React Suite library', value: true },
      { label: 'E-sign component', value: true },
      { label: 'QR Code component', value: true },
      { label: 'Grid component', value: true },
      { label: 'Repeater component', value: true },
      { label: 'SaaS use allowed', value: true },
      { label: 'OEM allowed', value: false },
      { label: 'Free updates (1 year)', value: true },
      { label: 'Source code included', value: true },
    ],
  },
]

type Props = {
  planType: 'subscription' | 'perpetual'
  showDetails: boolean
  onToggleDetails?: () => void
}

export function PricingCards({ planType, showDetails, onToggleDetails }: Props) {
  const plans = planType === 'subscription' ? subscriptionPlans : perpetualPlans

  return (
    <div className="max-w-6xl mx-auto grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-8" style={{ gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))' }}>
      {plans.map((plan) => (
        <PricingCard key={plan.name} {...plan} showDetails={showDetails} onToggleDetails={onToggleDetails} />
      ))}
    </div>
  )
}